tasks:
  - init: go env -w GO111MODULE=off &&
          go get github.com/devlights/mkghurl &&
          go env -u GO111MODULE
    command: if [ -n "$GITHUB_TOKEN" ]; then git remote set-url origin $(mkghurl blog-summary); fi
image:
  file: .gitpod.Dockerfile